# Generated by Django 3.2.6 on 2021-08-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_auto_20210820_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(blank=True, choices=[('EXPENSE', 'EXPENSE'), ('INCOME', 'INCOME')], max_length=200, null=True),
        ),
    ]
